POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE1MDQxMTYwLCJ1c2VySWQiOjJ9.GtM2rehTdFto4UrG95end38alB5tZcBbFSaiDl0shBI

{
  "name": "Test event 2",
  "description": "Another test event 2",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
