POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE1MTkyMjU0LCJ1c2VySWQiOjN9.7yeKBoViA4EPMP0UlMpul27VsfYO3q3efvjsft2hNJA

{
  "name": "Test event 6",
  "description": "Another test event 6",
  "location": "A test location",
  "dateTime": "2024-05-07T15:30:00.000Z"
}
